version: 2.1

defaults: &job_begining
  docker:
    - image: circleci/node:13.8.0


jobs:
  build:
    <<: *job_begining
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/npm_modules/
      - run: npm run lint

  test:
    <<: *job_begining
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *job_begining
    steps:
      - checkout
      - run: npm run audit

workflows:
  build-test-analyze-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test